style: github
template: CHANGELOG.tpl.md
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
        - style
        - refactor
        - perf
        - test
        - chore
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      docs: Documentation
      style: Style
      test: Tests
      chore: Chore
  header:
    pattern: "^(.*)$"
  notes:
    keywords:
      - BREAKING CHANGE
